[build]
  publish = "public"
  command = "hugo"

  [build.environment]
    HUGO_VERSION = "0.152.2"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200
